# App Info
ios_app_id                                : 881161030                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Best of all Malayalam Radios Wordlwide put together in this app.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Vimal Singh                                
your_link                                 : https://mobilitylabsapps.com                    
your_city                                 : San Francisco                                
email_address                             : support@mobilitylabsapps.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : mobilitylabsapp
github_username                           : vimalsingh
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Ad-Free Pro Version
    description                           : Pro version brings a completely distraction-free music listening experience of our top in class Malayalam Radio app.
    fontawesome_icon_name                 : magic
    
  - title                                 : Hand-curated Worldwide Radio Stations
    description                           : Over 100+ hand selected best-in-class radio stations from across the world playing Malayalam Music.
    fontawesome_icon_name                 : mobile

  - title                                 : Christian, Light/Film Music and Talk Radios
    description                           : A truly wide ranging music genres from Christian devotional to Yesudas, Mohanlal, Chitra, All India Radios staions for your listening pleasure.
    fontawesome_icon_name                 : play-circle

  - title                                 : Radio Stations Updated Remotely
    description                           : Remote updating of radio stations means you don't have to wait until new App version is released
    fontawesome_icon_name                 : sync

  - title                                 : Sleep Timer
    description                           : Put a timer (15.30,45 or 60 mins) and the app automatically stops playing at the expiraton of the time limit.
    fontawesome_icon_name                 : watch
  
  - title                                 : Favorite Radio Stations
    description                           : Mark your go-to radio stations as favorites!  Reach those stations in the 'Favorites' sections of the app
    fontawesome_icon_name                 : favorite

  - title                                 : Move to Next or Previous Radio stations from Radio Player
    description                           : Fast Forward and Rewind buttons in the Radio Player allow you to easily move forward or back to the next radio station.
    fontawesome_icon_name                 : arrow-alt-circle-down

  - title                                 : Album Art
    description                           : Where the radio station provides the correct song title, the App will display the album art for that song including the movie name, singer and song title
    fontawesome_icon_name                 : link

  - title                                 : Radio Controls from Lock Screen
    description                           : Control the App even the iPhone is locked from the lock screen navigation. Stop/Resume, FF/Rewind button allow you to control the app's navigation.
    fontawesome_icon_name                 : info-circle

  - title                                 : Apple Watch
    description                           : App can be controlled via Apple Watch as well. Stop/Pause, FF/Rewind buttons of the App can be used from Apple Watch
    fontawesome_icon_name                 : apple



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
